development:
  adapter: postgresql
  encoding: utf8
  database: sse_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sse_test
  pool: 5
  username: 
  password:

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: sse_production
#   pool: 5
#   username: 
#   password:
